### ISSUE TITLE
VSCode will have an squidly red error  creating a collection even the property is not required

### ISSUE THREAD

**Issue by ccfiel** [dkirchhof/payload-rest-client#1]
Typescript should not have an error if the property is not required. updatedAt and createdAt is not required property in the interface.

```
export interface Registration {
  id: string;
  name: string;
  email: string;
  site?: 'site1' | 'site2';
  department: string;
  contactNumber: string;
  tenant?: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
```
<img width="1018" alt="SCR-20231028-hrts" src="https://github.com/dkirchhof/payload-rest-client/assets/1788360/3eaf7c9e-b921-4e3d-8d1f-6d54a57b16a8">

**Comment by dkirchhof** [comment]
Id, updatedAt and createdAt should be optional. you're right. I will fix it.

**Comment by dkirchhof** [comment]
Just updated the library. Thanks for your report again :)
