### ISSUE TITLE
Should be able to omit required fields when making a draft document

### ISSUE THREAD

**Issue by parsadotsh** [dkirchhof/payload-rest-client#10]
Thank you for the wonderful library, Payload should really have this built-in.

Right now all required fields are required in Typescript as well when using 'create', however in the Admin UI we can make incomplete drafts without all the required fields inputted.

**Comment by dkirchhof** [comment]
Hey, thank you. Great idea.
I implemented a `createDraft` function, where all fields are optional. It will automatically pass a `drafts=true` param to the api.
