### ISSUE TITLE
feat: Option to overload the fetch function

### ISSUE THREAD

**Issue by matthijs166** [dkirchhof/payload-rest-client#14]
Hey there,

Awesome client, really helpful.
At the moment, we copy and paste the whole client in our svelte project.

The reason is that we want to overwrite the fetch function.
There is in Svelte a special fetch that will store a response in the HTML of a SSR and will reuse it on hydration.

Maybe if I got some time left I will create a PR.

**Comment by dkirchhof** [comment]
Done
