### ISSUE TITLE
feat: export errors types for 403 response handling

### ISSUE THREAD

**Issue by matthijs166** [dkirchhof/payload-rest-client#15]
This is a nice to have.

Sometimes I need to check if there is a 403 error.
I can't read out the response code because there is an error thrown.
So what I do is check the error type (was a bit of figuring out how to handle correct)

Only thing is that the error type is not exported by default, and now I import it like this:
```js
import {
UnauthorizedError,
ForbiddenError,
NotFoundError
} from 'payload-rest-client/dist/errors';
```

Don't know what the best way of handling is for this, but I think it will help some people.

**Comment by dkirchhof** [comment]
Added the error exports to the main file.
