### ISSUE TITLE
Can `qs` be removed so no dependencies?

### ISSUE THREAD

**Issue by nathanclevenger** [dkirchhof/payload-rest-client#2]
Great library here! 

Quick question - could `qs` be removed and just use `URLSearchParams`? 

I ask because the `qs` library is actually kindof big (like 10kb bundled / gzipped) for things like Edge and Cloudflare Workers where performance actually is impacted a lot by bundle size ... also not to mention client-size browser use as well ...

**Comment by dkirchhof** [comment]
Hey, thanks for your input. Since the queries could be a bit complex (where param), the native URLSearchParams wouldn't work. So I just built my own stringify function. Please check it out: https://github.com/dkirchhof/payload-rest-client/pull/4

**Comment by nathanclevenger** [comment]
Awesome - that looks great @dkirchhof!

**Comment by dkirchhof** [comment]
Hopefully it wouldn't break any serialization stuff. I will update the lib in a second.
