### ISSUE TITLE
Can Collection/Global be inferred?

### ISSUE THREAD

**Issue by nathanclevenger** [dkirchhof/payload-rest-client#3]
Again, huge fan of this library ... the one thing that annoys me though is I would really like to do `api.post.find({})` instead of `api.collections.post.find({})` ...

maybe this could be managed by following the Payload local API syntax with `findGlobal` and `updateGlobal` which is how you could infer the base path.

What do you think?  I know it's a breaking change, but it doesn't look like you have a ton of users yet ... although that is likely going to change shortly ...

**Comment by madaxen86** [comment]
This would probably lead to the problem that you could call findGlobal also on collections.
If you only need collections you could 
```ts
export const api = createClient(...).collections
```

**Comment by dkirchhof** [comment]
I tried to "merge" both proxies, but failed with this approach.
Inferring could work, since collections and globals differ slightly, but well ... The solution by @madaxen86 would be a lot simpler :D

Actually I like the separation.
