### ISSUE TITLE
Add auth operations to client

### ISSUE THREAD

**Issue by madaxen86** [dkirchhof/payload-rest-client#6]
As they are currently missing:
Do you plan to add the auth operations to the client?

**Comment by dkirchhof** [comment]
Actually I haven't used any auth operations for the rest api so far (only get requests for public endpoints), but I will have a look in the next days.

**Comment by dkirchhof** [comment]
Oh @madaxen86 did you mean these endpoints: https://payloadcms.com/docs/rest-api/overview#auth-operations?

**Comment by madaxen86** [comment]
> Oh @madaxen86 did you mean these endpoints: https://payloadcms.com/docs/rest-api/overview#auth-operations?

Yeah, exactly. 
Looking at your code it is probably just another "proxy" for the client with those 8 operations?

**Comment by dkirchhof** [comment]
https://github.com/dkirchhof/payload-rest-client/tree/feat/auth-operations

You can check out this branch. I just used the documentation as reference and didn't test it so far since I have no test project for that.
