### ISSUE TITLE
Narrow Relationships

### ISSUE THREAD

**Issue by madaxen86** [dkirchhof/payload-rest-client#9]
Example as reference what payload generates

```ts
type User = {
   id:string;
   email:string;
   ...
}
type Post = {
   id:string;
   author: {
      relationTo:string;
      value: string | User;
}

```

When getting posts we also receive the relation author as string | User.
But it actually will only be string if we pass fetchParam 
`{depth:0}`.
I'm not a typescript expert.
Shouldn't it be possible to narrow the relationship types based on the passed parameter for the collections find, findById and for the globals get functions?

**Comment by madaxen86** [comment]
Found this on the [discord](https://discord.com/channels/967097582721572934/967105150068092968/1018560707874267239) channel but that didn't work if I pass Post, but only if I pass Post["author"].

Hey guys! I created a typescript helper yesterday for narrowing relationship types on collections, based on the automatically generated payload types .


It is useful for when you know that you have fetched data with a depth > 0, and want typescript to be happy by changing relationship types from `string | CollectionType` or `(string | CollectionType)[]` to `CollectionType` and `CollectionType[]` respectively.
Let me know if you have any questions or feedback:

```ts
type CollectionsUnion = User | Organization | Role
export type NarrowRelationships<T> = {
    [K in keyof T]: T[K] extends (string | infer H)[]
        ? H extends CollectionsUnion
            ? H[]
            : T[K]
        : Exclude<T[K], string> extends never
        ? T[K]
        : Exclude<T[K], string>;
};

// Use it like:
type UserWithRelationships = NarrowRelationships<User> 
```

**Comment by dkirchhof** [comment]
Well, if you have a depth of 2 and nested types in nested type, you need to run this mapping type recursively.

```ts
export type NarrowRelationships<T> = {
    [K in keyof T]: T[K] extends (string | infer H)[]
        ? H extends CollectionsUnion
            ? H[]
            : T[K]
        : Exclude<T[K], string> extends never
        ? T[K]
        : NarrowRelationships<Exclude<T[K], string>>;
};
```

Actually this works (screenshot 1), but the types are ugly as hell. It doesn't show the "narrowed" type anymore (screenshot 2). 

1)
![image](https://github.com/dkirchhof/payload-rest-client/assets/2778643/b57b9615-35d9-4cd3-85c9-5ee971ee4fcc)

2)
![image](https://github.com/dkirchhof/payload-rest-client/assets/2778643/a124fd9a-b447-4ba3-9a7f-8be152482ca2)

---

Additionally the recursion must stop at some point (depending on the depth). 
So you need to extend this type several types like this:

```ts
export type NarrowRelationships1<T> = {
    [K in keyof T]: T[K] extends (string | infer H)[]
        ? H extends CollectionsUnion
            ? H[]
            : T[K]
        : Exclude<T[K], string> extends never
        ? T[K]
        : Exclude<T[K], string>;
};

export type NarrowRelationships2<T> = {
    [K in keyof T]: T[K] extends (string | infer H)[]
        ? H extends CollectionsUnion
            ? H[]
            : T[K]
        : Exclude<T[K], string> extends never
        ? T[K]
        : NarrowRelationships1<Exclude<T[K], string>>;
};

// ...
```

In the last mapping step it should infer the types as string only (not string | Location for example). Don't get it working.

---

So all in all I'm not really happy with it. Actually, you could use this type and include it somewhere in your project to cast your types by yourself.

Personally I use a lot of functions like this:

```ts
export const generateArticleUrl = (article: string | Article | undefined) => {
    if (article === undefined || typeof article === "string") {
        return "/404";
    }

    return `/articles/${article.slug}`;
};
```

So I don't need to use these type gymnastics and I'm safe if I use a wrong depth value.

**Comment by madaxen86** [comment]
Yeah I agree. Just stumbled over that I have to make some gymnastics on the frontend when I want to render relational data that I always have to narrow the type with 
´´´js 
typeof ... !== string && ...
```
But I agree, that the suggested approach would probably at some point cause runtime errors which should have be covered by typescript. As I'm not a typescript expert I wondered if it is possible to do somehow infer a value passed as a function arg, forgetting that TS does no runtime checking  🙄 .

**Comment by dkirchhof** [comment]
Do you mean something like custom type guards? These are a combination of runtime check + type narrowing.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards
